/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;
import static ru.otus.HelloOtus.hwGuavaCall;

public class App {
    public static void main(String... args) {

        System.out.println(hwGuavaCall());
        }
    }

